export const types = {
    SET_ACTIVE_USER: 'SET_ACTIVE_USER',

    // Load links
    REQUEST_LINKS: 'REQUEST_LINKS',
    RECEIVE_LINKS: 'RECEIVE_LINKS',
    ERROR_LINKS: 'ERROR_LINKS',

    // Add a new link
    REQUEST_ADD_LINK: 'REQUEST_ADD_LINK',
    RECEIVE_ADD_LINK: 'RECEIVE_ADD_LINK',
    ERROR_ADD_LINK: 'ERROR_ADD_LINK',

    // Delete a link
    REQUEST_DELETE_LINK: 'REQUEST_DELETE_LINK',
    RECEIVE_DELETE_LINK: 'RECEIVE_DELETE_LINK',
    ERROR_DELETE_LINK: 'ERROR_DELETE_LINK',

    // Edit a link
    REQUEST_EDIT_LINK: 'REQUEST_EDIT_LINK',
    RECEIVE_EDIT_LINK: 'RECEIVE_EDIT_LINK',
    ERROR_EDIT_LINK: 'ERROR_EDIT_LINK',

    // Bookmark a link
    REQUEST_BOOKMARK_LINK: 'REQUEST_BOOKMARK_LINK',
    RECEIVE_BOOKMARK_LINK: 'RECEIVE_BOOKMARK_LINK',
    ERROR_BOOKMARK_LINK: 'ERROR_BOOKMARK_LINK',

    // Toggle sidebar
    TOGGLE_SIDEBAR: 'TOGGLE_SIDEBAR', 
}