export const types = {
    SET_ACTIVE_USER: 'SET_ACTIVE_USER',

    // Load links
    REQUEST_LINKS: 'REQUEST_LINKS',
    RECEIVE_LINKS: 'RECEIVE_LINKS',
    ERROR_LINKS: 'ERROR_LINKS',

    // Add a new link
    TRY_ADD_LINK: 'TRY_ADD_LINK',
    CANCEL_ADD_LINK: 'CANCEL_ADD_LINK',
    REQUEST_ADD_LINK: 'REQUEST_ADD_LINK',
    RECEIVE_ADD_LINK: 'RECEIVE_ADD_LINK',
    ERROR_ADD_LINK: 'ERROR_ADD_LINK',

    // Delete a link
    TRY_DELETE_LINK: 'TRY_DELETE_LINK',
    CANCEL_DELETE_LINK: 'CANCEL_DELETE_LINK',
    REQUEST_DELETE_LINK: 'REQUEST_DELETE_LINK',
    RECEIVE_DELETE_LINK: 'RECEIVE_DELETE_LINK',
    ERROR_DELETE_LINK: 'ERROR_DELETE_LINK',

    // Edit a link
    TRY_EDIT_LINK: 'TRY_EDIT_LINK',
    CANCEL_EDIT_LINK: 'CANCEL_EDIT_LINK',
    REQUEST_EDIT_LINK: 'REQUEST_EDIT_LINK',
    RECEIVE_EDIT_LINK: 'RECEIVE_EDIT_LINK',
    ERROR_EDIT_LINK: 'ERROR_EDIT_LINK',

    // Link details
    SHOW_LINK_DETAILS: 'SHOW_LINK_DETAILS',
    HIDE_LINK_DETAILS: 'HIDE_LINK_DETAILS',


    // Bookmark a link
    REQUEST_BOOKMARK_LINK: 'REQUEST_BOOKMARK_LINK',
    RECEIVE_BOOKMARK_LINK: 'RECEIVE_BOOKMARK_LINK',
    ERROR_BOOKMARK_LINK: 'ERROR_BOOKMARK_LINK',
}