version: '3'

services:
    database:
        image: postgres
        volumes:
            - postgres-data:/var/lib/postgresql/data
        ports:
            - 25432:5432

    web:
        image: localhost:5000/war
        command: ./manage.py runserver 0.0.0.0:8000
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - 8000:8000
        volumes:
            - ./app:/app
            - node_modules:/app/node_modules
            - static:/app/static
        links:
            - database
            - webpack
        environment:
            PGDATABASE: postgres
            PGUSER: postgres
            PGPASSWORD: password
            PGHOST: database
            PGPORT: 5432
            DJANGO_SETTINGS_MODULE: links.settings.dev
            # Read from .env
            AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
            AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
    webpack:
        command: npm run dev
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - ./app:/app
            - node_modules:/app/node_modules
            - static:/app/static

volumes:
    postgres-data:
    node_modules:
    static:
