version: '3'

services:
    web:
        image: localhost:5000/war
        entrypoint: /app/start-web.sh
        ports:
            - 8004:8004
        environment:
            - DJANGO_SETTINGS_MODULE=links.settings.prod
            # Postgres
            - PGDATABASE=war
            - PGUSER=$WAR_DB_USER
            - PGPASSWORD=$WAR_DB_PASSWORD
            - PGHOST=$DOCKERHOST
            - PGPORT=5432
            # Pass-through
            - DJANGO_SECRET_KEY
            - LINKS_RAVEN_DSN
            - AWS_ACCESS_KEY_ID
            - AWS_SECRET_ACCESS_KEY
