const LINK_PAGE_TEMPLATE 			= '#link-page-template'
const USER_PAGE_TEMPLATE 			= '#user-page-template'
const LINK_TEMPLATE 				= '#link-template'
const USER_FORM_TEMPLATE 			= '#user-form-template'
const NAVBAR_USER_TEMPLATE 			= '#navbar-user-template'

const PAGE_ROOT						= '#page-root'
const WELCOME_PAGE 					= '#welcome-page'
const USER_PAGE 					= '#user-page'
const LINK_PAGE 					= '#link-page'
const LINK_LIST 					= '#link-list'
const USER_NAVBAR 					= '#users-navbar'

const EDIT_USERS_BUTTON				= '#edit-users-button'
const NAVBAR_USERS_LIST 			= '#users-navbar-list'

const NEW_LINK_BUTTON 				= '#new-item-button'
const NEW_LINK_FORM 				= '#new-item-form'
const NEW_LINK_URL_CLASS 			= '.url'
const NEW_LINK_TITLE_CLASS 			= '.title'
const NEW_LINK_CANCEL_BUTTON_CLASS 	= '.cancel'
const NEW_LINK_SUBMIT_BUTTON_CLASS 	= '.submit'

const ADD_USER_FORM 				= '#new-user-form'
const ADD_USER_BUTTON 				= '#new-user-button'
const CONFIRM_ADD_USER_BUTTON 		= '#confirm-new-user-button'
const CANCEL_ADD_USER_BUTTON 		= '#cancel-new-user-button'
const USERNAME_TEXTBOX 				= '#new-user-name'

const LINK_DELETE_BUTTON			= '.link-delete-button'
const LINK_DELETE_FORM 				= '.link-delete-form'
const CONFIRM_LINK_DELETE_BUTTON  	= '.delete'
const CANCEL_LINK_DELETE_BUTTON		= '.cancel'

const LINK_EDIT_BUTTON				= '.link-edit-button'
const LINK_EDIT_FORM 				= '.link-edit-form'
const CONFIRM_LINK_EDIT_BUTTON  	= '.submit'
const CANCEL_LINK_EDIT_BUTTON		= '.cancel'
const LINK_EDIT_TITLE				= '.title'
const LINK_EDIT_URL					= '.url'
const LINK_HYPERLINK				= 'a'