# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-20 09:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20170219_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='url',
            field=models.CharField(max_length=250),
        ),
    ]
