# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 14:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20170220_2043'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='description',
            field=models.TextField(default=b''),
        ),
    ]
