# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-25 01:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_link_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
