# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-17 09:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0007_auto_20170325_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='bookmarkers',
            field=models.ManyToManyField(related_name='bookmarks', to=settings.AUTH_USER_MODEL),
        ),
    ]
